# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .
    restart: always
    env_file: 
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      db:
        condition: service_started
    profiles:
      - debug

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    profiles:
      - core
      - debug

  dbui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@db:${MONGO_DB_PORT}/
    depends_on:
      db:
        condition: service_started
    profiles:
      - core
      - debug
