# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      dockerfile: .
    restart: always
    env_file: 
      - development.env
    port:
      - 4000:4000
    depends_on:
      - db
    condition: service_started
    profiles:
      - debug

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    port:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    condition: service_started
    profiles:
      - core
      - debug

  dbui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
    depends_on:
      - db
    profiles:
      - core
      - debug
